name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          echo "[greet]
                image = alpine
                args = --entrypoint /bin/sh
                cmd = -c 'echo Hello \${NAME}'
            " > ~/.dckr
          cat ~/.dckr
      - name: Execute a test command
        shell: script -q -e -c "bash {0}" # Hack to acquire TTY
        run: |
          ./dckr greet -e NAME="World"
          exit
          grep "Hello World" typescript
      - name: List all entries
        shell: script -q -e -c "bash {0}" # Hack to acquire TTY
        run: |
          ./dckr -ls
          exit
          grep "greet" typescript
      - name: Print help
        shell: script -q -e -c "bash {0}" # Hack to acquire TTY
        run: |
          ./dckr --help
          exit
          grep "Usage" typescript
